# this switches to the workspace w/ my browser
# before opening the url
command = "hyprctl dispatch workspace 2 && xdg-open"

[[entries]]
default = true
name = "URL"
url = "https://%TERM%"

[[entries]]
default = true
name = "Kagi"
url = "https://www.kagi.com/search?q=%TERM%"

[[entries]]
default = true
name = "Duck Duck Go"
url = "https://www.duckduckgo.com?q=%TERM%"

